/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TatuadoresRouteImport } from './routes/tatuadores'
import { Route as TatuadorAcessoRouteImport } from './routes/tatuador-acesso'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroTatuadorRouteImport } from './routes/cadastro-tatuador'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AuthenticatedTatuadorRouteImport } from './routes/_authenticated/tatuador'
import { Route as AuthenticatedPoliticasRouteImport } from './routes/_authenticated/politicas'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedCarrinhoRouteImport } from './routes/_authenticated/carrinho'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated/campanhas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTatuadorIndexRouteImport } from './routes/_authenticated/tatuador.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as AuthenticatedTatuadorTermosRouteImport } from './routes/_authenticated/tatuador.termos'
import { Route as AuthenticatedTatuadorSolicitarPagamentoRouteImport } from './routes/_authenticated/tatuador.solicitar-pagamento'
import { Route as AuthenticatedTatuadorRateioRouteImport } from './routes/_authenticated/tatuador.rateio'
import { Route as AuthenticatedTatuadorPlanoRouteImport } from './routes/_authenticated/tatuador.plano'
import { Route as AuthenticatedTatuadorPerfilRouteImport } from './routes/_authenticated/tatuador.perfil'
import { Route as AuthenticatedTatuadorMensalidadeRouteImport } from './routes/_authenticated/tatuador.mensalidade'
import { Route as AuthenticatedTatuadorDivulgacaoRouteImport } from './routes/_authenticated/tatuador.divulgacao'
import { Route as AuthenticatedTatuadorDadosRouteImport } from './routes/_authenticated/tatuador.dados'
import { Route as AuthenticatedTatuadorAssinaturaRouteImport } from './routes/_authenticated/tatuador.assinatura'
import { Route as AuthenticatedAdminVendasRouteImport } from './routes/_authenticated/admin.vendas'
import { Route as AuthenticatedAdminTatuadoresRouteImport } from './routes/_authenticated/admin.tatuadores'
import { Route as AuthenticatedAdminSaquesRouteImport } from './routes/_authenticated/admin.saques'
import { Route as AuthenticatedAdminRateiosRouteImport } from './routes/_authenticated/admin.rateios'
import { Route as AuthenticatedAdminMensalidadesRouteImport } from './routes/_authenticated/admin.mensalidades'
import { Route as AuthenticatedAdminEstilosRouteImport } from './routes/_authenticated/admin.estilos'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCampanhasRouteImport } from './routes/_authenticated/admin.campanhas'
import { Route as AuthenticatedAdminAplicacoesRouteImport } from './routes/_authenticated/admin.aplicacoes'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TatuadoresRoute = TatuadoresRouteImport.update({
  id: '/tatuadores',
  path: '/tatuadores',
  getParentRoute: () => rootRouteImport,
} as any)
const TatuadorAcessoRoute = TatuadorAcessoRouteImport.update({
  id: '/tatuador-acesso',
  path: '/tatuador-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroTatuadorRoute = CadastroTatuadorRouteImport.update({
  id: '/cadastro-tatuador',
  path: '/cadastro-tatuador',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTatuadorRoute = AuthenticatedTatuadorRouteImport.update({
  id: '/tatuador',
  path: '/tatuador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliticasRoute = AuthenticatedPoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarrinhoRoute = AuthenticatedCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTatuadorIndexRoute =
  AuthenticatedTatuadorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTatuadorTermosRoute =
  AuthenticatedTatuadorTermosRouteImport.update({
    id: '/termos',
    path: '/termos',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorSolicitarPagamentoRoute =
  AuthenticatedTatuadorSolicitarPagamentoRouteImport.update({
    id: '/solicitar-pagamento',
    path: '/solicitar-pagamento',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorRateioRoute =
  AuthenticatedTatuadorRateioRouteImport.update({
    id: '/rateio',
    path: '/rateio',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorPlanoRoute =
  AuthenticatedTatuadorPlanoRouteImport.update({
    id: '/plano',
    path: '/plano',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorPerfilRoute =
  AuthenticatedTatuadorPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorMensalidadeRoute =
  AuthenticatedTatuadorMensalidadeRouteImport.update({
    id: '/mensalidade',
    path: '/mensalidade',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorDivulgacaoRoute =
  AuthenticatedTatuadorDivulgacaoRouteImport.update({
    id: '/divulgacao',
    path: '/divulgacao',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorDadosRoute =
  AuthenticatedTatuadorDadosRouteImport.update({
    id: '/dados',
    path: '/dados',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedTatuadorAssinaturaRoute =
  AuthenticatedTatuadorAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedTatuadorRoute,
  } as any)
const AuthenticatedAdminVendasRoute =
  AuthenticatedAdminVendasRouteImport.update({
    id: '/vendas',
    path: '/vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTatuadoresRoute =
  AuthenticatedAdminTatuadoresRouteImport.update({
    id: '/tatuadores',
    path: '/tatuadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaquesRoute =
  AuthenticatedAdminSaquesRouteImport.update({
    id: '/saques',
    path: '/saques',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRateiosRoute =
  AuthenticatedAdminRateiosRouteImport.update({
    id: '/rateios',
    path: '/rateios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMensalidadesRoute =
  AuthenticatedAdminMensalidadesRouteImport.update({
    id: '/mensalidades',
    path: '/mensalidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstilosRoute =
  AuthenticatedAdminEstilosRouteImport.update({
    id: '/estilos',
    path: '/estilos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampanhasRoute =
  AuthenticatedAdminCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAplicacoesRoute =
  AuthenticatedAdminAplicacoesRouteImport.update({
    id: '/aplicacoes',
    path: '/aplicacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-tatuador': typeof CadastroTatuadorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tatuador-acesso': typeof TatuadorAcessoRoute
  '/tatuadores': typeof TatuadoresRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/politicas': typeof AuthenticatedPoliticasRoute
  '/tatuador': typeof AuthenticatedTatuadorRouteWithChildren
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/aplicacoes': typeof AuthenticatedAdminAplicacoesRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estilos': typeof AuthenticatedAdminEstilosRoute
  '/admin/mensalidades': typeof AuthenticatedAdminMensalidadesRoute
  '/admin/rateios': typeof AuthenticatedAdminRateiosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/tatuadores': typeof AuthenticatedAdminTatuadoresRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/tatuador/assinatura': typeof AuthenticatedTatuadorAssinaturaRoute
  '/tatuador/dados': typeof AuthenticatedTatuadorDadosRoute
  '/tatuador/divulgacao': typeof AuthenticatedTatuadorDivulgacaoRoute
  '/tatuador/mensalidade': typeof AuthenticatedTatuadorMensalidadeRoute
  '/tatuador/perfil': typeof AuthenticatedTatuadorPerfilRoute
  '/tatuador/plano': typeof AuthenticatedTatuadorPlanoRoute
  '/tatuador/rateio': typeof AuthenticatedTatuadorRateioRoute
  '/tatuador/solicitar-pagamento': typeof AuthenticatedTatuadorSolicitarPagamentoRoute
  '/tatuador/termos': typeof AuthenticatedTatuadorTermosRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tatuador/': typeof AuthenticatedTatuadorIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-tatuador': typeof CadastroTatuadorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tatuador-acesso': typeof TatuadorAcessoRoute
  '/tatuadores': typeof TatuadoresRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/politicas': typeof AuthenticatedPoliticasRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/aplicacoes': typeof AuthenticatedAdminAplicacoesRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estilos': typeof AuthenticatedAdminEstilosRoute
  '/admin/mensalidades': typeof AuthenticatedAdminMensalidadesRoute
  '/admin/rateios': typeof AuthenticatedAdminRateiosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/tatuadores': typeof AuthenticatedAdminTatuadoresRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/tatuador/assinatura': typeof AuthenticatedTatuadorAssinaturaRoute
  '/tatuador/dados': typeof AuthenticatedTatuadorDadosRoute
  '/tatuador/divulgacao': typeof AuthenticatedTatuadorDivulgacaoRoute
  '/tatuador/mensalidade': typeof AuthenticatedTatuadorMensalidadeRoute
  '/tatuador/perfil': typeof AuthenticatedTatuadorPerfilRoute
  '/tatuador/plano': typeof AuthenticatedTatuadorPlanoRoute
  '/tatuador/rateio': typeof AuthenticatedTatuadorRateioRoute
  '/tatuador/solicitar-pagamento': typeof AuthenticatedTatuadorSolicitarPagamentoRoute
  '/tatuador/termos': typeof AuthenticatedTatuadorTermosRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tatuador': typeof AuthenticatedTatuadorIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cadastro-tatuador': typeof CadastroTatuadorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tatuador-acesso': typeof TatuadorAcessoRoute
  '/tatuadores': typeof TatuadoresRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/carrinho': typeof AuthenticatedCarrinhoRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/politicas': typeof AuthenticatedPoliticasRoute
  '/_authenticated/tatuador': typeof AuthenticatedTatuadorRouteWithChildren
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/admin/aplicacoes': typeof AuthenticatedAdminAplicacoesRoute
  '/_authenticated/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estilos': typeof AuthenticatedAdminEstilosRoute
  '/_authenticated/admin/mensalidades': typeof AuthenticatedAdminMensalidadesRoute
  '/_authenticated/admin/rateios': typeof AuthenticatedAdminRateiosRoute
  '/_authenticated/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/_authenticated/admin/tatuadores': typeof AuthenticatedAdminTatuadoresRoute
  '/_authenticated/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/_authenticated/tatuador/assinatura': typeof AuthenticatedTatuadorAssinaturaRoute
  '/_authenticated/tatuador/dados': typeof AuthenticatedTatuadorDadosRoute
  '/_authenticated/tatuador/divulgacao': typeof AuthenticatedTatuadorDivulgacaoRoute
  '/_authenticated/tatuador/mensalidade': typeof AuthenticatedTatuadorMensalidadeRoute
  '/_authenticated/tatuador/perfil': typeof AuthenticatedTatuadorPerfilRoute
  '/_authenticated/tatuador/plano': typeof AuthenticatedTatuadorPlanoRoute
  '/_authenticated/tatuador/rateio': typeof AuthenticatedTatuadorRateioRoute
  '/_authenticated/tatuador/solicitar-pagamento': typeof AuthenticatedTatuadorSolicitarPagamentoRoute
  '/_authenticated/tatuador/termos': typeof AuthenticatedTatuadorTermosRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tatuador/': typeof AuthenticatedTatuadorIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cadastro-tatuador'
    | '/login'
    | '/reset-password'
    | '/tatuador-acesso'
    | '/tatuadores'
    | '/admin'
    | '/campanhas'
    | '/carrinho'
    | '/conta'
    | '/politicas'
    | '/tatuador'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/admin/aplicacoes'
    | '/admin/campanhas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/estilos'
    | '/admin/mensalidades'
    | '/admin/rateios'
    | '/admin/saques'
    | '/admin/tatuadores'
    | '/admin/vendas'
    | '/tatuador/assinatura'
    | '/tatuador/dados'
    | '/tatuador/divulgacao'
    | '/tatuador/mensalidade'
    | '/tatuador/perfil'
    | '/tatuador/plano'
    | '/tatuador/rateio'
    | '/tatuador/solicitar-pagamento'
    | '/tatuador/termos'
    | '/api/public/asaas-webhook'
    | '/api/public/mercadopago-webhook'
    | '/admin/'
    | '/tatuador/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cadastro-tatuador'
    | '/login'
    | '/reset-password'
    | '/tatuador-acesso'
    | '/tatuadores'
    | '/campanhas'
    | '/carrinho'
    | '/conta'
    | '/politicas'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/admin/aplicacoes'
    | '/admin/campanhas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/estilos'
    | '/admin/mensalidades'
    | '/admin/rateios'
    | '/admin/saques'
    | '/admin/tatuadores'
    | '/admin/vendas'
    | '/tatuador/assinatura'
    | '/tatuador/dados'
    | '/tatuador/divulgacao'
    | '/tatuador/mensalidade'
    | '/tatuador/perfil'
    | '/tatuador/plano'
    | '/tatuador/rateio'
    | '/tatuador/solicitar-pagamento'
    | '/tatuador/termos'
    | '/api/public/asaas-webhook'
    | '/api/public/mercadopago-webhook'
    | '/admin'
    | '/tatuador'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/cadastro-tatuador'
    | '/login'
    | '/reset-password'
    | '/tatuador-acesso'
    | '/tatuadores'
    | '/_authenticated/admin'
    | '/_authenticated/campanhas'
    | '/_authenticated/carrinho'
    | '/_authenticated/conta'
    | '/_authenticated/politicas'
    | '/_authenticated/tatuador'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/_authenticated/admin/aplicacoes'
    | '/_authenticated/admin/campanhas'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estilos'
    | '/_authenticated/admin/mensalidades'
    | '/_authenticated/admin/rateios'
    | '/_authenticated/admin/saques'
    | '/_authenticated/admin/tatuadores'
    | '/_authenticated/admin/vendas'
    | '/_authenticated/tatuador/assinatura'
    | '/_authenticated/tatuador/dados'
    | '/_authenticated/tatuador/divulgacao'
    | '/_authenticated/tatuador/mensalidade'
    | '/_authenticated/tatuador/perfil'
    | '/_authenticated/tatuador/plano'
    | '/_authenticated/tatuador/rateio'
    | '/_authenticated/tatuador/solicitar-pagamento'
    | '/_authenticated/tatuador/termos'
    | '/api/public/asaas-webhook'
    | '/api/public/mercadopago-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/tatuador/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CadastroTatuadorRoute: typeof CadastroTatuadorRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TatuadorAcessoRoute: typeof TatuadorAcessoRoute
  TatuadoresRoute: typeof TatuadoresRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tatuadores': {
      id: '/tatuadores'
      path: '/tatuadores'
      fullPath: '/tatuadores'
      preLoaderRoute: typeof TatuadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tatuador-acesso': {
      id: '/tatuador-acesso'
      path: '/tatuador-acesso'
      fullPath: '/tatuador-acesso'
      preLoaderRoute: typeof TatuadorAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-tatuador': {
      id: '/cadastro-tatuador'
      path: '/cadastro-tatuador'
      fullPath: '/cadastro-tatuador'
      preLoaderRoute: typeof CadastroTatuadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tatuador': {
      id: '/_authenticated/tatuador'
      path: '/tatuador'
      fullPath: '/tatuador'
      preLoaderRoute: typeof AuthenticatedTatuadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/politicas': {
      id: '/_authenticated/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof AuthenticatedPoliticasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carrinho': {
      id: '/_authenticated/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthenticatedCarrinhoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tatuador/': {
      id: '/_authenticated/tatuador/'
      path: '/'
      fullPath: '/tatuador/'
      preLoaderRoute: typeof AuthenticatedTatuadorIndexRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tatuador/termos': {
      id: '/_authenticated/tatuador/termos'
      path: '/termos'
      fullPath: '/tatuador/termos'
      preLoaderRoute: typeof AuthenticatedTatuadorTermosRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/solicitar-pagamento': {
      id: '/_authenticated/tatuador/solicitar-pagamento'
      path: '/solicitar-pagamento'
      fullPath: '/tatuador/solicitar-pagamento'
      preLoaderRoute: typeof AuthenticatedTatuadorSolicitarPagamentoRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/rateio': {
      id: '/_authenticated/tatuador/rateio'
      path: '/rateio'
      fullPath: '/tatuador/rateio'
      preLoaderRoute: typeof AuthenticatedTatuadorRateioRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/plano': {
      id: '/_authenticated/tatuador/plano'
      path: '/plano'
      fullPath: '/tatuador/plano'
      preLoaderRoute: typeof AuthenticatedTatuadorPlanoRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/perfil': {
      id: '/_authenticated/tatuador/perfil'
      path: '/perfil'
      fullPath: '/tatuador/perfil'
      preLoaderRoute: typeof AuthenticatedTatuadorPerfilRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/mensalidade': {
      id: '/_authenticated/tatuador/mensalidade'
      path: '/mensalidade'
      fullPath: '/tatuador/mensalidade'
      preLoaderRoute: typeof AuthenticatedTatuadorMensalidadeRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/divulgacao': {
      id: '/_authenticated/tatuador/divulgacao'
      path: '/divulgacao'
      fullPath: '/tatuador/divulgacao'
      preLoaderRoute: typeof AuthenticatedTatuadorDivulgacaoRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/dados': {
      id: '/_authenticated/tatuador/dados'
      path: '/dados'
      fullPath: '/tatuador/dados'
      preLoaderRoute: typeof AuthenticatedTatuadorDadosRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/tatuador/assinatura': {
      id: '/_authenticated/tatuador/assinatura'
      path: '/assinatura'
      fullPath: '/tatuador/assinatura'
      preLoaderRoute: typeof AuthenticatedTatuadorAssinaturaRouteImport
      parentRoute: typeof AuthenticatedTatuadorRoute
    }
    '/_authenticated/admin/vendas': {
      id: '/_authenticated/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AuthenticatedAdminVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tatuadores': {
      id: '/_authenticated/admin/tatuadores'
      path: '/tatuadores'
      fullPath: '/admin/tatuadores'
      preLoaderRoute: typeof AuthenticatedAdminTatuadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/saques': {
      id: '/_authenticated/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AuthenticatedAdminSaquesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rateios': {
      id: '/_authenticated/admin/rateios'
      path: '/rateios'
      fullPath: '/admin/rateios'
      preLoaderRoute: typeof AuthenticatedAdminRateiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensalidades': {
      id: '/_authenticated/admin/mensalidades'
      path: '/mensalidades'
      fullPath: '/admin/mensalidades'
      preLoaderRoute: typeof AuthenticatedAdminMensalidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estilos': {
      id: '/_authenticated/admin/estilos'
      path: '/estilos'
      fullPath: '/admin/estilos'
      preLoaderRoute: typeof AuthenticatedAdminEstilosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campanhas': {
      id: '/_authenticated/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aplicacoes': {
      id: '/_authenticated/admin/aplicacoes'
      path: '/aplicacoes'
      fullPath: '/admin/aplicacoes'
      preLoaderRoute: typeof AuthenticatedAdminAplicacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAplicacoesRoute: typeof AuthenticatedAdminAplicacoesRoute
  AuthenticatedAdminCampanhasRoute: typeof AuthenticatedAdminCampanhasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstilosRoute: typeof AuthenticatedAdminEstilosRoute
  AuthenticatedAdminMensalidadesRoute: typeof AuthenticatedAdminMensalidadesRoute
  AuthenticatedAdminRateiosRoute: typeof AuthenticatedAdminRateiosRoute
  AuthenticatedAdminSaquesRoute: typeof AuthenticatedAdminSaquesRoute
  AuthenticatedAdminTatuadoresRoute: typeof AuthenticatedAdminTatuadoresRoute
  AuthenticatedAdminVendasRoute: typeof AuthenticatedAdminVendasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAplicacoesRoute: AuthenticatedAdminAplicacoesRoute,
  AuthenticatedAdminCampanhasRoute: AuthenticatedAdminCampanhasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEstilosRoute: AuthenticatedAdminEstilosRoute,
  AuthenticatedAdminMensalidadesRoute: AuthenticatedAdminMensalidadesRoute,
  AuthenticatedAdminRateiosRoute: AuthenticatedAdminRateiosRoute,
  AuthenticatedAdminSaquesRoute: AuthenticatedAdminSaquesRoute,
  AuthenticatedAdminTatuadoresRoute: AuthenticatedAdminTatuadoresRoute,
  AuthenticatedAdminVendasRoute: AuthenticatedAdminVendasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTatuadorRouteChildren {
  AuthenticatedTatuadorAssinaturaRoute: typeof AuthenticatedTatuadorAssinaturaRoute
  AuthenticatedTatuadorDadosRoute: typeof AuthenticatedTatuadorDadosRoute
  AuthenticatedTatuadorDivulgacaoRoute: typeof AuthenticatedTatuadorDivulgacaoRoute
  AuthenticatedTatuadorMensalidadeRoute: typeof AuthenticatedTatuadorMensalidadeRoute
  AuthenticatedTatuadorPerfilRoute: typeof AuthenticatedTatuadorPerfilRoute
  AuthenticatedTatuadorPlanoRoute: typeof AuthenticatedTatuadorPlanoRoute
  AuthenticatedTatuadorRateioRoute: typeof AuthenticatedTatuadorRateioRoute
  AuthenticatedTatuadorSolicitarPagamentoRoute: typeof AuthenticatedTatuadorSolicitarPagamentoRoute
  AuthenticatedTatuadorTermosRoute: typeof AuthenticatedTatuadorTermosRoute
  AuthenticatedTatuadorIndexRoute: typeof AuthenticatedTatuadorIndexRoute
}

const AuthenticatedTatuadorRouteChildren: AuthenticatedTatuadorRouteChildren = {
  AuthenticatedTatuadorAssinaturaRoute: AuthenticatedTatuadorAssinaturaRoute,
  AuthenticatedTatuadorDadosRoute: AuthenticatedTatuadorDadosRoute,
  AuthenticatedTatuadorDivulgacaoRoute: AuthenticatedTatuadorDivulgacaoRoute,
  AuthenticatedTatuadorMensalidadeRoute: AuthenticatedTatuadorMensalidadeRoute,
  AuthenticatedTatuadorPerfilRoute: AuthenticatedTatuadorPerfilRoute,
  AuthenticatedTatuadorPlanoRoute: AuthenticatedTatuadorPlanoRoute,
  AuthenticatedTatuadorRateioRoute: AuthenticatedTatuadorRateioRoute,
  AuthenticatedTatuadorSolicitarPagamentoRoute:
    AuthenticatedTatuadorSolicitarPagamentoRoute,
  AuthenticatedTatuadorTermosRoute: AuthenticatedTatuadorTermosRoute,
  AuthenticatedTatuadorIndexRoute: AuthenticatedTatuadorIndexRoute,
}

const AuthenticatedTatuadorRouteWithChildren =
  AuthenticatedTatuadorRoute._addFileChildren(
    AuthenticatedTatuadorRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedCarrinhoRoute: typeof AuthenticatedCarrinhoRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedPoliticasRoute: typeof AuthenticatedPoliticasRoute
  AuthenticatedTatuadorRoute: typeof AuthenticatedTatuadorRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedCarrinhoRoute: AuthenticatedCarrinhoRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedPoliticasRoute: AuthenticatedPoliticasRoute,
  AuthenticatedTatuadorRoute: AuthenticatedTatuadorRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CadastroTatuadorRoute: CadastroTatuadorRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TatuadorAcessoRoute: TatuadorAcessoRoute,
  TatuadoresRoute: TatuadoresRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
